# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-12 21:58
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bagogold', '0169_auto_20180206_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckpointFII',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField(verbose_name='Ano')),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade no ano')),
                ('preco_medio', models.DecimalField(decimal_places=4, max_digits=11, verbose_name='Pre\xe7o m\xe9dio')),
            ],
        ),
        migrations.CreateModel(
            name='CheckpointProventosFII',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField(verbose_name='Ano')),
                ('valor', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='Valor da poupan\xe7a de proventos')),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chkp_prov_fii_novo', to='bagogold.Investidor')),
            ],
        ),
        migrations.CreateModel(
            name='EventoAgrupamentoFII',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('proporcao', models.DecimalField(decimal_places=12, max_digits=13, validators=[django.core.validators.MaxValueValidator(Decimal('0.999999999999'))], verbose_name='Propor\xe7\xe3o de agrupamento')),
                ('valor_fracao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Valor para as fra\xe7\xf5es')),
            ],
        ),
        migrations.CreateModel(
            name='EventoDesdobramentoFII',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('proporcao', models.DecimalField(decimal_places=12, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('1.000000000001'))], verbose_name='Propor\xe7\xe3o de desdobramento')),
                ('valor_fracao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Valor para as fra\xe7\xf5es')),
            ],
        ),
        migrations.CreateModel(
            name='EventoIncorporacaoFII',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='FII',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True, verbose_name='Ticker do FII')),
                ('encerrado', models.BooleanField(default=False, verbose_name='FII encerrado?')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fii_novo', to='bagogold.Empresa')),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoFII',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Pre\xe7o unit\xe1rio')),
                ('data', models.DateField(verbose_name='Data de refer\xeancia')),
                ('oficial_bovespa', models.BooleanField(default=False, verbose_name='Oficial Bovespa?')),
                ('fii', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fii.FII', unique_for_date=b'data')),
            ],
        ),
        migrations.CreateModel(
            name='OperacaoFII',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Pre\xe7o unit\xe1rio')),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('corretagem', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Corretagem')),
                ('emolumentos', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Emolumentos')),
                ('tipo_operacao', models.CharField(max_length=1, verbose_name='Tipo de opera\xe7\xe3o')),
                ('consolidada', models.NullBooleanField(verbose_name='Consolidada?')),
                ('fii', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fii.FII')),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op_fii_novo', to='bagogold.Investidor')),
            ],
        ),
        migrations.CreateModel(
            name='ProventoFII',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_unitario', models.DecimalField(decimal_places=16, max_digits=20, verbose_name='Valor unit\xe1rio')),
                ('tipo_provento', models.CharField(max_length=1, verbose_name='Tipo de provento')),
                ('data_ex', models.DateField(verbose_name='Data EX')),
                ('data_pagamento', models.DateField(verbose_name='Data do pagamento')),
                ('oficial_bovespa', models.BooleanField(default=False, verbose_name='Oficial Bovespa?')),
                ('fii', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fii.FII')),
            ],
        ),
        migrations.CreateModel(
            name='UsoProventosOperacaoFII',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_utilizada', models.DecimalField(blank=True, decimal_places=2, max_digits=11, verbose_name='Quantidade de proventos utilizada')),
                ('divisao_operacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uso_prov_fii_novo', to='bagogold.DivisaoOperacaoFII')),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fii.OperacaoFII')),
            ],
        ),
        migrations.CreateModel(
            name='ValorDiarioFII',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Hor\xe1rio')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Pre\xe7o unit\xe1rio')),
                ('fii', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fii.FII')),
            ],
        ),
        migrations.AddField(
            model_name='eventoincorporacaofii',
            name='fii',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fii.FII'),
        ),
        migrations.AddField(
            model_name='eventoincorporacaofii',
            name='novo_fii',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incorporacao', to='fii.FII'),
        ),
        migrations.AddField(
            model_name='eventodesdobramentofii',
            name='fii',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fii.FII'),
        ),
        migrations.AddField(
            model_name='eventoagrupamentofii',
            name='fii',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fii.FII'),
        ),
        migrations.AddField(
            model_name='checkpointfii',
            name='fii',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chkp_fii_novo', to='fii.FII'),
        ),
        migrations.AddField(
            model_name='checkpointfii',
            name='investidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chkp_fii_novo', to='bagogold.Investidor'),
        ),
        migrations.AlterUniqueTogether(
            name='proventofii',
            unique_together=set([('data_ex', 'data_pagamento', 'fii', 'valor_unitario', 'oficial_bovespa')]),
        ),
        migrations.AlterUniqueTogether(
            name='historicofii',
            unique_together=set([('fii', 'data')]),
        ),
        migrations.AlterUniqueTogether(
            name='eventoincorporacaofii',
            unique_together=set([('fii', 'data')]),
        ),
        migrations.AlterUniqueTogether(
            name='eventodesdobramentofii',
            unique_together=set([('fii', 'data')]),
        ),
        migrations.AlterUniqueTogether(
            name='eventoagrupamentofii',
            unique_together=set([('fii', 'data')]),
        ),
        migrations.AlterUniqueTogether(
            name='checkpointproventosfii',
            unique_together=set([('ano', 'investidor')]),
        ),
        migrations.AlterUniqueTogether(
            name='checkpointfii',
            unique_together=set([('fii', 'ano', 'investidor')]),
        ),
    ]
