# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-13 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fii', '0002_auto_20180212_2018'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventoincorporacaofii',
            unique_together=set([('fii',)]),
        ),
    ]
