# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-08 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fii', '0004_auto_20180422_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proventofii',
            name='tipo_provento',
            field=models.CharField(choices=[(b'R', b'Rendimento'), (b'A', b'Amortiza\xc3\xa7\xc3\xa3o')], max_length=1, verbose_name='Tipo de provento'),
        ),
    ]
