# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-22 18:11
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bagogold', '0174_checkpointdivisaoletracambio_divisaooperacaoletracambio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckpointLetraCambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField(verbose_name='Ano')),
                ('qtd_restante', models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantidade restante da opera\xe7\xe3o')),
                ('qtd_atualizada', models.DecimalField(decimal_places=8, max_digits=17, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))], verbose_name='Quantidade atualizada da opera\xe7\xe3o')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoCarenciaLetraCambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carencia', models.IntegerField(verbose_name='Per\xedodo de car\xeancia')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data da varia\xe7\xe3o')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoPorcentagemLetraCambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentagem', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentagem de rendimento')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data da varia\xe7\xe3o')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoValorMinimoInvestimentoLetraCambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_minimo', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor m\xednimo para investimento')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data da varia\xe7\xe3o')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoVencimentoLetraCambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vencimento', models.IntegerField(verbose_name='Per\xedodo de vencimento')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data da varia\xe7\xe3o')),
            ],
        ),
        migrations.CreateModel(
            name='LetraCambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('tipo_rendimento', models.PositiveSmallIntegerField(verbose_name='Tipo de rendimento')),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Investidor')),
            ],
        ),
        migrations.CreateModel(
            name='OperacaoLetraCambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Quantidade investida/resgatada')),
                ('data', models.DateField(verbose_name='Data da opera\xe7\xe3o')),
                ('tipo_operacao', models.CharField(max_length=1, verbose_name='Tipo de opera\xe7\xe3o')),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Investidor')),
                ('lc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lc.LetraCambio')),
            ],
        ),
        migrations.CreateModel(
            name='OperacaoVendaLetraCambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacao_compra', to='lc.OperacaoLetraCambio')),
                ('operacao_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacao_venda', to='lc.OperacaoLetraCambio')),
            ],
        ),
        migrations.AddField(
            model_name='historicovencimentoletracambio',
            name='lc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lc.LetraCambio'),
        ),
        migrations.AddField(
            model_name='historicovalorminimoinvestimentoletracambio',
            name='lc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lc.LetraCambio'),
        ),
        migrations.AddField(
            model_name='historicoporcentagemletracambio',
            name='lc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lc.LetraCambio'),
        ),
        migrations.AddField(
            model_name='historicocarencialetracambio',
            name='lc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lc.LetraCambio'),
        ),
        migrations.AddField(
            model_name='checkpointletracambio',
            name='operacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lc.OperacaoLetraCambio'),
        ),
        migrations.AlterUniqueTogether(
            name='operacaovendaletracambio',
            unique_together=set([('operacao_compra', 'operacao_venda')]),
        ),
        migrations.AlterUniqueTogether(
            name='checkpointletracambio',
            unique_together=set([('operacao', 'ano')]),
        ),
    ]
