# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0037_auto_20160229_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacaoVendaLetraCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.OperacaoLetraCredito')),
            ],
        ),
    ]
