# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 22:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0038_operacaovendaletracredito'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulo',
            name='data_inicio',
            field=models.DateField(default=datetime.date(2016, 3, 20), verbose_name='Data de in\xedcio'),
            preserve_default=False,
        ),
    ]
