# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0039_titulo_data_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisao',
            name='valor_objetivo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Objetivo'),
        ),
        migrations.AlterField(
            model_name='historicocarencialetracredito',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data da varia\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='historicoporcentagemletracredito',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data da varia\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='operacaoacao',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='operacaofii',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='operacaotitulo',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
    ]
