# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0040_auto_20160321_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisao',
            name='valor_objetivo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, verbose_name='Objetivo'),
        ),
    ]
