# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0042_auto_20160321_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usoproventosoperacaofii',
            name='qtd_utilizada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, verbose_name='Quantidade de proventos utilizada'),
        ),
        migrations.AlterUniqueTogether(
            name='divisaooperacaoacoes',
            unique_together=set([('divisao', 'operacao')]),
        ),
        migrations.AlterUniqueTogether(
            name='divisaooperacaofii',
            unique_together=set([('divisao', 'operacao')]),
        ),
        migrations.AlterUniqueTogether(
            name='divisaooperacaotd',
            unique_together=set([('divisao', 'operacao')]),
        ),
    ]
