# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0043_auto_20160321_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicocarencialetracredito',
            name='carencia',
            field=models.IntegerField(default=1, verbose_name='Per\xedodo de car\xeancia'),
        ),
    ]
