# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0045_auto_20160321_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacaovendaletracredito',
            name='operacao_venda',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='operacao_venda', to='bagogold.OperacaoLetraCredito'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operacaovendaletracredito',
            name='operacao_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacao_compra', to='bagogold.OperacaoLetraCredito'),
        ),
    ]
