# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0046_auto_20160325_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisaoPrincipal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Divisao')),
            ],
        ),
        migrations.AlterField(
            model_name='operacaoletracredito',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Quantidade investida/resgatada'),
        ),
        migrations.AlterUniqueTogether(
            name='operacaovendaletracredito',
            unique_together=set([('operacao_compra', 'operacao_venda')]),
        ),
    ]
