# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0047_auto_20160331_2144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DivisaoOperacaoAcoes',
            new_name='DivisaoOperacaoAcao',
        ),
        migrations.AlterField(
            model_name='fii',
            name='ticker',
            field=models.CharField(max_length=10, unique=True, verbose_name='Ticker da a\xe7\xe3o'),
        ),
    ]
