# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0047_auto_20160331_2144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DivisaoOperacaoAcoes',
            new_name='DivisaoOperacaoAcao',
        ),
    ]
