# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0048_auto_20160405_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='proventofii',
            name='url_documento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL do documento'),
        ),
    ]
