# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0049_proventofii_url_documento'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proventofii',
            unique_together=set([('data_ex', 'data_pagamento'), ('fii',)]),
        ),
    ]
