# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0050_auto_20160410_1142'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historicoacao',
            unique_together=set([('acao', 'data')]),
        ),
    ]
