# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0051_auto_20160410_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acao',
            options={'ordering': ['ticker']},
        ),
        migrations.AlterUniqueTogether(
            name='proventofii',
            unique_together=set([('data_ex', 'data_pagamento', 'fii')]),
        ),
    ]
