# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0052_auto_20160410_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoValorMinimoInvestimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_minimo', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor m\xednimo para investimento')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data da varia\xe7\xe3o')),
                ('letra_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.LetraCredito')),
            ],
        ),
        migrations.AlterModelOptions(
            name='fii',
            options={'ordering': ['ticker']},
        ),
        migrations.AddField(
            model_name='historicoacao',
            name='oficial_bovespa',
            field=models.BooleanField(default=False, verbose_name='Oficial Bovespa?'),
        ),
        migrations.AddField(
            model_name='historicofii',
            name='oficial_bovespa',
            field=models.BooleanField(default=False, verbose_name='Oficial Bovespa?'),
        ),
    ]
