# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 22:33
from __future__ import unicode_literals
from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0053_auto_20160421_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='provento',
            name='observacao',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Observa\xe7\xe3o'),
        ),
        migrations.CreateModel(
            name='TransferenciaEntreDivisoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data da transfer\xeancia')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Quantidade transferida')),
                ('divisao_cedente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='divisao_cedente', to='bagogold.Divisao')),
                ('divisao_recebedora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='divisao_recebedora', to='bagogold.Divisao')),
            ],
        ),
        migrations.AlterField(
            model_name='fii',
            name='ticker',
            field=models.CharField(max_length=10, unique=True, verbose_name='Ticker do FII'),
        ),
    ]
