# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0053_auto_20160421_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='provento',
            name='observacao',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Observa\xe7\xe3o'),
        ),
    ]
