# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0054_auto_20160424_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferenciaentredivisoes',
            name='investimento_destino',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name=b'Investimento de destino'),
        ),
        migrations.AddField(
            model_name='transferenciaentredivisoes',
            name='investimento_origem',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name=b'Investimento de origem'),
        ),
    ]
