# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0055_empresa_codigo_cvm'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nome_pregao',
            field=models.CharField(default='Teste', max_length=30, verbose_name=b'Nome de preg\xc3\xa3o'),
            preserve_default=False,
        ),
    ]
