# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0058_auto_20160504_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='provento',
            name='oficial_bovespa',
            field=models.BooleanField(default=False, verbose_name='Oficial Bovespa?'),
        ),
    ]
