# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 04:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0059_provento_oficial_bovespa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corretagem_padrao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Corretagem padr\xe3o')),
                ('tipo_corretagem', models.CharField(blank=True, max_length=1, null=True, verbose_name='Tipo de corretagem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
