# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-20 21:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0059_provento_oficial_bovespa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corretagem_padrao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Corretagem padr\xe3o')),
                ('tipo_corretagem', models.CharField(blank=True, max_length=1, null=True, verbose_name='Tipo de corretagem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('tipo', models.PositiveSmallIntegerField(verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoCarenciaCDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carencia', models.IntegerField(verbose_name='Per\xedodo de car\xeancia')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data da varia\xe7\xe3o')),
                ('cdb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.CDB')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoCarenciaRDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carencia', models.IntegerField(verbose_name='Per\xedodo de car\xeancia')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data da varia\xe7\xe3o')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoPorcentagemCDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentagem', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentagem de rendimento')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data da varia\xe7\xe3o')),
                ('cdb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.CDB')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoPorcentagemRDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentagem', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentagem de rendimento')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data da varia\xe7\xe3o')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoValorMinimoInvestimentoCDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_minimo', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor m\xednimo para investimento')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data da varia\xe7\xe3o')),
                ('cdb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.CDB')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoValorMinimoInvestimentoRDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_minimo', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor m\xednimo para investimento')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data da varia\xe7\xe3o')),
            ],
        ),
        migrations.CreateModel(
            name='OperacaoCDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Quantidade investida/resgatada')),
                ('data', models.DateField(verbose_name='Data da opera\xe7\xe3o')),
                ('tipo_operacao', models.CharField(max_length=1, verbose_name='Tipo de opera\xe7\xe3o')),
                ('cdb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.CDB')),
            ],
        ),
        migrations.CreateModel(
            name='OperacaoRDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Quantidade investida/resgatada')),
                ('data', models.DateField(verbose_name='Data da opera\xe7\xe3o')),
                ('tipo_operacao', models.CharField(max_length=1, verbose_name='Tipo de opera\xe7\xe3o')),
            ],
        ),
        migrations.CreateModel(
            name='OperacaoVendaCDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacao_compra', to='bagogold.OperacaoCDB')),
                ('operacao_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacao_venda', to='bagogold.OperacaoCDB')),
            ],
        ),
        migrations.CreateModel(
            name='OperacaoVendaRDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacao_compra', to='bagogold.OperacaoRDB')),
                ('operacao_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacao_venda', to='bagogold.OperacaoRDB')),
            ],
        ),
        migrations.CreateModel(
            name='RDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('tipo', models.PositiveSmallIntegerField(verbose_name='Tipo')),
            ],
        ),
        migrations.AddField(
            model_name='operacaordb',
            name='rdb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.RDB'),
        ),
        migrations.AddField(
            model_name='historicovalorminimoinvestimentordb',
            name='rdb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.RDB'),
        ),
        migrations.AddField(
            model_name='historicoporcentagemrdb',
            name='rdb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.RDB'),
        ),
        migrations.AddField(
            model_name='historicocarenciardb',
            name='rdb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.RDB'),
        ),
        migrations.AlterUniqueTogether(
            name='operacaovendardb',
            unique_together=set([('operacao_compra', 'operacao_venda')]),
        ),
        migrations.AlterUniqueTogether(
            name='operacaovendacdb',
            unique_together=set([('operacao_compra', 'operacao_venda')]),
        ),
    ]
