# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-20 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0060_auto_20160620_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdb',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='rdb',
            name='tipo',
        ),
        migrations.AddField(
            model_name='cdb',
            name='tipo_rendimento',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Tipo de rendimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rdb',
            name='tipo_rendimento',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Tipo de rendimento'),
            preserve_default=False,
        ),
    ]
