# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-23 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0062_auto_20160621_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDB_RDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('tipo', models.CharField(max_length=1, verbose_name='Tipo')),
                ('tipo_rendimento', models.PositiveSmallIntegerField(verbose_name='Tipo de rendimento')),
            ],
        ),
        migrations.CreateModel(
            name='OperacaoCDB_RDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Quantidade investida/resgatada')),
                ('data', models.DateField(verbose_name='Data da opera\xe7\xe3o')),
                ('tipo_operacao', models.CharField(max_length=1, verbose_name='Tipo de opera\xe7\xe3o')),
                ('investimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.CDB_RDB')),
            ],
        ),
        migrations.RenameModel(
            old_name='DivisaoOperacaoCDB',
            new_name='DivisaoOperacaoCDB_RDB',
        ),
        migrations.RenameModel(
            old_name='HistoricoCarenciaCDB',
            new_name='HistoricoCarenciaCDB_RDB',
        ),
        migrations.RenameModel(
            old_name='HistoricoPorcentagemCDB',
            new_name='HistoricoPorcentagemCDB_RDB',
        ),
        migrations.RenameModel(
            old_name='HistoricoValorMinimoInvestimentoCDB',
            new_name='HistoricoValorMinimoInvestimentoCDB_RDB',
        ),
        migrations.RenameModel(
            old_name='OperacaoVendaRDB',
            new_name='OperacaoVendaCDB_RDB',
        ),
        migrations.AlterUniqueTogether(
            name='divisaooperacaordb',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='divisaooperacaordb',
            name='divisao',
        ),
        migrations.RemoveField(
            model_name='divisaooperacaordb',
            name='operacao',
        ),
        migrations.RemoveField(
            model_name='historicocarenciardb',
            name='rdb',
        ),
        migrations.RemoveField(
            model_name='historicoporcentagemrdb',
            name='rdb',
        ),
        migrations.RemoveField(
            model_name='historicovalorminimoinvestimentordb',
            name='rdb',
        ),
        migrations.RemoveField(
            model_name='operacaocdb',
            name='cdb',
        ),
        migrations.RemoveField(
            model_name='operacaordb',
            name='rdb',
        ),
        migrations.AlterUniqueTogether(
            name='operacaovendacdb',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='operacaovendacdb',
            name='operacao_compra',
        ),
        migrations.RemoveField(
            model_name='operacaovendacdb',
            name='operacao_venda',
        ),
        migrations.AlterField(
            model_name='divisaooperacaocdb_rdb',
            name='operacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.OperacaoCDB_RDB'),
        ),
        migrations.AlterField(
            model_name='historicocarenciacdb_rdb',
            name='cdb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.CDB_RDB'),
        ),
        migrations.AlterField(
            model_name='historicoporcentagemcdb_rdb',
            name='cdb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.CDB_RDB'),
        ),
        migrations.AlterField(
            model_name='historicovalorminimoinvestimentocdb_rdb',
            name='cdb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.CDB_RDB'),
        ),
        migrations.AlterField(
            model_name='operacaovendacdb_rdb',
            name='operacao_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacao_compra', to='bagogold.OperacaoCDB_RDB'),
        ),
        migrations.AlterField(
            model_name='operacaovendacdb_rdb',
            name='operacao_venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacao_venda', to='bagogold.OperacaoCDB_RDB'),
        ),
        migrations.DeleteModel(
            name='CDB',
        ),
        migrations.DeleteModel(
            name='DivisaoOperacaoRDB',
        ),
        migrations.DeleteModel(
            name='HistoricoCarenciaRDB',
        ),
        migrations.DeleteModel(
            name='HistoricoPorcentagemRDB',
        ),
        migrations.DeleteModel(
            name='HistoricoValorMinimoInvestimentoRDB',
        ),
        migrations.DeleteModel(
            name='OperacaoCDB',
        ),
        migrations.DeleteModel(
            name='OperacaoRDB',
        ),
        migrations.DeleteModel(
            name='OperacaoVendaCDB',
        ),
        migrations.DeleteModel(
            name='RDB',
        ),
    ]
