# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-23 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0063_auto_20160623_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicocarenciacdb_rdb',
            old_name='cdb',
            new_name='cdb_rdb',
        ),
        migrations.RenameField(
            model_name='historicoporcentagemcdb_rdb',
            old_name='cdb',
            new_name='cdb_rdb',
        ),
        migrations.RenameField(
            model_name='historicovalorminimoinvestimentocdb_rdb',
            old_name='cdb',
            new_name='cdb_rdb',
        ),
    ]
