# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-30 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0064_auto_20160623_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacaocdb_rdb',
            name='investidor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bagogold.Investidor'),
            preserve_default=False,
        ),
    ]
