# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-30 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0065_operacaocdb_rdb_investidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdb_rdb',
            name='investidor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bagogold.Investidor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='letracredito',
            name='investidor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bagogold.Investidor'),
            preserve_default=False,
        ),
    ]
