# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-04 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0066_auto_20160630_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoIPCA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor IPCA')),
                ('mes', models.SmallIntegerField(verbose_name='M\xeas')),
                ('ano', models.SmallIntegerField(verbose_name='Ano')),
            ],
        ),
    ]
