# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-03 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0066_auto_20160630_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferenciaentredivisoes',
            name='descricao',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descri\xe7\xe3o'),
        ),
    ]
