# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-03 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0066_auto_20160630_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicocorretagempadrao',
            name='investidor',
        ),
        migrations.AddField(
            model_name='investidor',
            name='auto_atualizar_saldo',
            field=models.BooleanField(default=False, verbose_name='Atualizar saldo automaticamente?'),
        ),
        migrations.DeleteModel(
            name='HistoricoCorretagemPadrao',
        ),
    ]
