# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-08 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0068_auto_20160705_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundoinvestimento',
            name='taxa_adm',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='Taxa de administra\xe7\xe3o'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicovalorcotas',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='historicovalorcotas',
            name='valor_cota',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Valor da cota'),
        ),
    ]
