# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-14 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0069_auto_20160708_0254'),
        ('bagogold', '0067_transferenciaentredivisoes_descricao'),
        ('bagogold', '0068_auto_20160705_1147'),
    ]

    operations = [
    ]
