# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-14 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0070_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacaocompravenda',
            name='quantidade',
            field=models.IntegerField(default=0, verbose_name='Quantidade de a\xe7\xf5es'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='operacaocompravenda',
            unique_together=set([('compra', 'venda')]),
        ),
    ]
