# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-12 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0071_auto_20160714_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisaoprincipal',
            name='investidor',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='bagogold.Investidor'),
            preserve_default=False,
        ),
    ]
