# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-24 17:50
from __future__ import unicode_literals

import bagogold.bagogold.models.gerador_proventos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0072_documentobovespa_pendencia_proventoacaodocumento_proventofiidocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentobovespa',
            name='data_referencia',
            field=models.DateField(default=None, verbose_name='Data de refer\xeancia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentobovespa',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to=bagogold.bagogold.models.gerador_proventos.ticker_path),
        ),
        migrations.AlterUniqueTogether(
            name='documentobovespa',
            unique_together=set([('empresa', 'protocolo')]),
        ),
    ]
