# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-12 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0072_divisaoprincipal_investidor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divisaoprincipal',
            name='id',
        ),
        migrations.AlterField(
            model_name='divisaoprincipal',
            name='investidor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bagogold.Investidor'),
        ),
    ]
