# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-12 18:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0073_auto_20161012_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investidor',
            name='id',
        ),
        migrations.AlterField(
            model_name='investidor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
