# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-14 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0073_auto_20161012_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisaooperacaoacao',
            name='uso_proventos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, verbose_name=b'Utiliza\xc3\xa7\xc3\xa3o de proventos'),
        ),
    ]
