# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-15 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0074_divisaooperacaoacao_uso_proventos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divisaooperacaoacao',
            name='uso_proventos',
        ),
    ]
