# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-25 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0074_pendencia_data_criacao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentoBovespa',
            new_name='DocumentoProventoBovespa',
        ),
        migrations.RenameModel(
            old_name='Pendencia',
            new_name='PendenciaDocumentoProvento',
        ),
    ]
