# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-15 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0075_remove_divisaooperacaoacao_uso_proventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usoproventosoperacaoacao',
            name='divisao_operacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bagogold.DivisaoOperacaoAcao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='divisaooperacaoacao',
            name='quantidade',
            field=models.IntegerField(verbose_name=b'Quantidade (em a\xc3\xa7\xc3\xb5es)'),
        ),
        migrations.AlterField(
            model_name='divisaooperacaocdb_rdb',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name=b'Quantidade (em reais)'),
        ),
        migrations.AlterField(
            model_name='divisaooperacaofii',
            name='quantidade',
            field=models.IntegerField(verbose_name=b'Quantidade (em pap\xc3\xa9is)'),
        ),
        migrations.AlterField(
            model_name='divisaooperacaofundoinvestimento',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name=b'Quantidade (em cotas)'),
        ),
        migrations.AlterField(
            model_name='divisaooperacaolc',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name=b'Quantidade (em reais)'),
        ),
        migrations.AlterField(
            model_name='divisaooperacaotd',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Quantidade (em t\xedtulos)'),
        ),
    ]
