# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-15 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0076_auto_20161015_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usoproventosoperacaoacao',
            name='divisao_operacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bagogold.DivisaoOperacaoAcao'),
        ),
    ]
