# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-16 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0077_auto_20161015_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='usoproventosoperacaofii',
            name='divisao_operacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bagogold.DivisaoOperacaoFII'),
            preserve_default=False,
        ),
    ]
