# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-16 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0078_usoproventosoperacaofii_divisao_operacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usoproventosoperacaofii',
            name='divisao_operacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bagogold.DivisaoOperacaoFII'),
        ),
    ]
