# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-16 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0078_usoproventosoperacaofii_divisao_operacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operacaofundoinvestimento',
            old_name='quantidade_cotas',
            new_name='quantidade',
        ),
    ]
