# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-20 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0079_auto_20161016_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operacaofundoinvestimento',
            old_name='quantidade_cotas',
            new_name='quantidade',
        ),
    ]
