# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-02 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0080_auto_20161020_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarregamentoMetronic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carregar_dados', models.BooleanField(default=False, verbose_name='Carregar dados')),
                ('ultimo_carregamento', models.DateTimeField(auto_now=True, verbose_name='\xdaltimo carregamento')),
            ],
        ),
    ]
