# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-24 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0071_auto_20160714_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoBovespa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='URL do documento')),
                ('protocolo', models.CharField(max_length=10, verbose_name='Protocolo')),
                ('tipo', models.CharField(max_length=1, verbose_name='Tipo de provento')),
                ('documento', models.FileField(blank=True, null=True, upload_to=b'doc proventos/')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Pendencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.DocumentoBovespa')),
            ],
        ),
        migrations.CreateModel(
            name='ProventoAcaoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.DocumentoBovespa')),
                ('provento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Provento')),
            ],
        ),
        migrations.CreateModel(
            name='ProventoFIIDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.DocumentoBovespa')),
                ('provento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.ProventoFII')),
            ],
        ),
    ]
