# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-25 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0083_auto_20160724_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendencia',
            name='data_criacao',
            field=models.DateField(default=None, editable=False),
            preserve_default=False,
        ),
    ]
