# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-04 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0085_auto_20160724_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendenciadocumentoprovento',
            name='tipo',
            field=models.CharField(default=b'L', max_length=1, verbose_name='Tipo de pend\xeancia'),
        ),
    ]
