# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-06 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0087_auto_20161104_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoProventoTemporarioAcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento_frac', models.DateField(blank=True, null=True, verbose_name='Data do pagamento de fra\xe7\xf5es')),
                ('valor_calculo_frac', models.DecimalField(decimal_places=10, default=0, max_digits=14, verbose_name='Valor para c\xe1lculo das fra\xe7\xf5es')),
                ('acao_recebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Acao')),
            ],
        ),
        migrations.CreateModel(
            name='ProventoAcaoDescritoDocumentoBovespa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_unitario', models.DecimalField(decimal_places=12, max_digits=16, verbose_name='Valor unit\xe1rio')),
                ('tipo_provento', models.CharField(max_length=1, verbose_name='Tipo de provento')),
                ('data_ex', models.DateField(verbose_name='Data EX')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('observacao', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observa\xe7\xe3o')),
                ('oficial_bovespa', models.BooleanField(default=False, verbose_name='Oficial Bovespa?')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Acao')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.DocumentoProventoBovespa')),
            ],
        ),
        migrations.CreateModel(
            name='ProventoFIIDescritoDocumentoBovespa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_unitario', models.DecimalField(decimal_places=9, max_digits=13, verbose_name='Valor unit\xe1rio')),
                ('data_ex', models.DateField(verbose_name='Data EX')),
                ('data_pagamento', models.DateField(verbose_name='Data do pagamento')),
                ('url_documento', models.CharField(blank=True, max_length=200, null=True, verbose_name='URL do documento')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.DocumentoProventoBovespa')),
                ('fii', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.FII')),
            ],
        ),
        migrations.AddField(
            model_name='proventoacaodocumento',
            name='versao',
            field=models.SmallIntegerField(default=None, verbose_name='Vers\xe3o'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proventofiidocumento',
            name='versao',
            field=models.SmallIntegerField(default=None, verbose_name='Vers\xe3o'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acaoproventotemporarioacao',
            name='provento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.ProventoAcaoDescritoDocumentoBovespa'),
        ),
        migrations.AlterUniqueTogether(
            name='proventofiidescritodocumentobovespa',
            unique_together=set([('data_ex', 'data_pagamento', 'fii')]),
        ),
    ]
