# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-06 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0089_auto_20161105_2352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcaoProventoTemporarioAcao',
            new_name='AcaoProventoAcaoDescritoDocumentoBovespa',
        ),
    ]
