# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-09 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0091_auto_20161106_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proventoacaodescritodocumentobovespa',
            name='oficial_bovespa',
        ),
    ]
