# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-11 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0092_remove_proventoacaodescritodocumentobovespa_oficial_bovespa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoproventobovespa',
            options={'permissions': (('pode_gerar_proventos', 'Pode gerar proventos a partir de documentos'),)},
        ),
    ]
