# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-11 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0094_auto_20161111_0309'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proventofiidocumento',
            unique_together=set([]),
        ),
    ]
