# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-20 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0096_auto_20161111_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestidorRecusaDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=500, verbose_name='Motivo da recusa')),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Investidor')),
                ('pendencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bagogold.PendenciaDocumentoProvento')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='investidorrecusadocumento',
            unique_together=set([('pendencia', 'investidor')]),
        ),
    ]
