# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-20 21:06
from __future__ import unicode_literals
from django.db import migrations, models
from django.utils import timezone



class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0097_auto_20161120_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='investidorleituradocumento',
            name='data_leitura',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now(), verbose_name='Data da leitura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investidorrecusadocumento',
            name='data_recusa',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now(), verbose_name='Data da recusa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investidorresponsavelpendencia',
            name='data_alocacao',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now(), verbose_name='Data da aloca\xe7\xe3o'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investidorvalidacaodocumento',
            name='data_validacao',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now(), verbose_name='Data da valida\xe7\xe3o'),
            preserve_default=False,
        ),
    ]
