# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-20 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0098_auto_20161120_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendenciadocumentoprovento',
            name='data_criacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
