# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-24 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0099_auto_20161120_1908'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='provento',
            unique_together=set([('acao', 'valor_unitario', 'data_ex', 'data_pagamento')]),
        ),
    ]
