# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-16 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0100_auto_20161124_0040'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proventoacaodescritodocumentobovespa',
            unique_together=set([('data_ex', 'data_pagamento', 'acao', 'tipo_provento')]),
        ),
        migrations.AlterUniqueTogether(
            name='proventoacaodocumento',
            unique_together=set([('documento', 'versao')]),
        ),
        migrations.AlterUniqueTogether(
            name='proventofiidocumento',
            unique_together=set([('documento', 'versao')]),
        ),
    ]
