# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-16 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0101_auto_20161216_2118'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proventoacaodocumento',
            unique_together=set([('documento', 'versao', 'provento')]),
        ),
        migrations.AlterUniqueTogether(
            name='proventofiidocumento',
            unique_together=set([('documento', 'versao', 'provento')]),
        ),
    ]
