# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-17 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0102_auto_20161216_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proventoacaodocumento',
            name='provento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Provento'),
        ),
        migrations.AlterField(
            model_name='proventofiidocumento',
            name='provento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.ProventoFII'),
        ),
        migrations.AlterUniqueTogether(
            name='proventoacaodocumento',
            unique_together=set([('documento', 'provento'), ('versao', 'provento')]),
        ),
        migrations.AlterUniqueTogether(
            name='proventofiidocumento',
            unique_together=set([('documento', 'provento'), ('versao', 'provento')]),
        ),
    ]
