# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-17 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0103_auto_20161217_0009'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='provento',
            unique_together=set([('acao', 'valor_unitario', 'data_ex', 'data_pagamento', 'tipo_provento')]),
        ),
    ]
