# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-18 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0104_auto_20161217_1435'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investidorrecusadocumento',
            unique_together=set([]),
        ),
    ]
