# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-19 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0106_auto_20161218_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investidorrecusadocumento',
            name='pendencia',
        ),
        migrations.AddField(
            model_name='investidorrecusadocumento',
            name='documento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bagogold.DocumentoProventoBovespa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investidorrecusadocumento',
            name='responsavel_leitura',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='leituras_recusadas', to='bagogold.Investidor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investidorrecusadocumento',
            name='investidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras_que_recusou', to='bagogold.Investidor'),
        ),
    ]
