# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-20 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0107_auto_20161219_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='proventofii',
            name='oficial_bovespa',
            field=models.BooleanField(default=False, verbose_name='Oficial Bovespa?'),
        ),
    ]
