# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-05 01:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0108_proventofii_oficial_bovespa'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proventoacaodescritodocumentobovespa',
            unique_together=set([('data_ex', 'data_pagamento', 'acao', 'tipo_provento', 'valor_unitario')]),
        ),
        migrations.AlterUniqueTogether(
            name='proventofii',
            unique_together=set([('data_ex', 'data_pagamento', 'fii', 'valor_unitario')]),
        ),
        migrations.AlterUniqueTogether(
            name='proventofiidescritodocumentobovespa',
            unique_together=set([('data_ex', 'data_pagamento', 'fii', 'valor_unitario')]),
        ),
    ]
