# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-12 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0109_auto_20170104_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoTaxaSelic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('taxa', models.DecimalField(decimal_places=9, max_digits=11, unique_for_date=b'data', verbose_name='Taxa di\xe1ria')),
            ],
        ),
    ]
