# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-12 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0110_historicotaxaselic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicotaxaselic',
            old_name='taxa',
            new_name='taxa_diaria',
        ),
    ]
