# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-17 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0111_auto_20170112_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debenture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='C\xf3digo')),
                ('tipo_indexacao', models.PositiveSmallIntegerField(verbose_name='Tipo de indexa\xe7\xe3o')),
                ('porcentagem', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Porcentagem sobre indexa\xe7\xe3o')),
                ('juros_adicional', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Juros adicional')),
                ('data_emissao', models.DateField(verbose_name='Data de emiss\xe3o')),
                ('valor_emissao', models.DecimalField(decimal_places=8, max_digits=15, verbose_name='Valor nominal na emiss\xe3o')),
                ('data_inicio_rendimento', models.DateField(verbose_name='Data de in\xedcio do rendimento')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de vencimento')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de fim')),
                ('incentivada', models.BooleanField(verbose_name='\xc9 incentivada?')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoValorDebenture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_nominal', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Valor nominal')),
                ('juros', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Juros')),
                ('premio', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Pr\xeamio')),
                ('data', models.DateField(verbose_name='Data')),
                ('debenture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Debenture')),
            ],
        ),
        migrations.CreateModel(
            name='OperacaoDebenture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_unitario', models.DecimalField(decimal_places=8, max_digits=15, verbose_name='Pre\xe7o unit\xe1rio')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('taxa', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Taxa')),
                ('debenture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Debenture')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='debenture',
            unique_together=set([('codigo',)]),
        ),
    ]
