# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-17 05:00
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0114_auto_20170117_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debenture',
            name='tipo_indexacao',
        ),
        migrations.AddField(
            model_name='debenture',
            name='indice',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='\xcdndice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amortizacaodebenture',
            name='tipo',
            field=models.PositiveSmallIntegerField(verbose_name='Tipo de amortiza\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='debenture',
            name='porcentagem',
            field=models.DecimalField(decimal_places=3, default=Decimal('100'), max_digits=6, verbose_name='Porcentagem sobre \xedndice'),
        ),
    ]
