# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-17 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0115_auto_20170117_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debenture',
            name='valor_emissao',
            field=models.DecimalField(decimal_places=8, max_digits=17, verbose_name='Valor nominal na emiss\xe3o'),
        ),
    ]
