# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-21 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0116_auto_20170117_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debenture',
            name='indice',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Prefixado'), (2, b'IPCA'), (3, b'DI'), (4, b'IGP-M'), (5, b'SELIC')], verbose_name='\xcdndice'),
        ),
    ]
