# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-21 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0117_auto_20170121_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amortizacaodebenture',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Indefinido'), (1, 'Percentual fixo sobre o valor nominal atualizado em per\xedodos n\xe3o uniformes'), (2, 'Percentual fixo sobre o valor nominal atualizado em per\xedodos uniformes'), (3, 'Percentual fixo sobre o valor nominal de emiss\xe3o em per\xedodos n\xe3o uniformes'), (4, 'Percentual fixo sobre o valor nominal de emiss\xe3o em per\xedodos uniformes'), (5, 'Percentual vari\xe1vel sobre o valor nominal atualizado em per\xedodos n\xe3o uniformes'), (6, 'Percentual vari\xe1vel sobre o valor nominal atualizado em per\xedodos uniformes'), (7, 'Percentual vari\xe1vel sobre o valor nominal de emiss\xe3o em per\xedodos n\xe3o uniformes'), (8, 'Percentual vari\xe1vel sobre o valor nominal de emiss\xe3o em per\xedodos uniformes')], verbose_name='Tipo de amortiza\xe7\xe3o'),
        ),
    ]
