# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-22 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0118_auto_20170121_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amortizacaodebenture',
            name='carencia',
            field=models.DateField(blank=True, null=True, verbose_name='Car\xeancia'),
        ),
        migrations.AlterField(
            model_name='jurosdebenture',
            name='carencia',
            field=models.DateField(blank=True, null=True, verbose_name='Car\xeancia'),
        ),
        migrations.AlterField(
            model_name='premiodebenture',
            name='carencia',
            field=models.DateField(blank=True, null=True, verbose_name='Car\xeancia'),
        ),
    ]
