# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-23 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0119_auto_20170122_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisaoOperacaoDebenture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=11, verbose_name=b'Quantidade (em reais)')),
                ('divisao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Divisao')),
            ],
        ),
        migrations.AddField(
            model_name='operacaodebenture',
            name='tipo_operacao',
            field=models.CharField(default='C', max_length=1, verbose_name='Tipo de opera\xe7\xe3o'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divisaooperacaodebenture',
            name='operacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.OperacaoDebenture'),
        ),
        migrations.AlterUniqueTogether(
            name='divisaooperacaodebenture',
            unique_together=set([('divisao', 'operacao')]),
        ),
    ]
