# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-26 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0120_auto_20170123_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacaodebenture',
            name='investidor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bagogold.Investidor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='divisaooperacaodebenture',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name=b'Quantidade (em t\xc3\xadtulos)'),
        ),
    ]
