# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-27 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0121_auto_20170126_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoproventobovespa',
            name='tipo_documento',
            field=models.CharField(default='', max_length=50, verbose_name='Tipo de documento'),
            preserve_default=False,
        ),
    ]
