# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-02 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0121_auto_20170126_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amortizacaodebenture',
            name='debenture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Debenture'),
        ),
        migrations.AlterField(
            model_name='jurosdebenture',
            name='debenture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Debenture'),
        ),
        migrations.AlterField(
            model_name='premiodebenture',
            name='debenture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Debenture'),
        ),
        migrations.AddField(
            model_name='amortizacaodebenture',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jurosdebenture',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premiodebenture',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
