# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-02 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0122_auto_20170202_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amortizacaodebenture',
            name='debenture',
        ),
        migrations.RemoveField(
            model_name='jurosdebenture',
            name='debenture',
        ),
        migrations.RemoveField(
            model_name='premiodebenture',
            name='debenture',
        ),
    ]
