# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-27 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0122_documentoproventobovespa_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoproventobovespa',
            name='tipo_documento',
            field=models.CharField(max_length=100, verbose_name='Tipo de documento'),
        ),
    ]
