# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-02 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0123_auto_20170202_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='amortizacaodebenture',
            name='debenture',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bagogold.Debenture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jurosdebenture',
            name='debenture',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bagogold.Debenture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premiodebenture',
            name='debenture',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bagogold.Debenture'),
            preserve_default=False,
        ),
    ]
