# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-03 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0124_auto_20170202_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amortizacaodebenture',
            name='debenture',
        ),
        migrations.RemoveField(
            model_name='jurosdebenture',
            name='debenture',
        ),
        migrations.RemoveField(
            model_name='premiodebenture',
            name='debenture',
        ),
        migrations.AlterUniqueTogether(
            name='provento',
            unique_together=set([('acao', 'valor_unitario', 'data_ex', 'data_pagamento', 'tipo_provento', 'oficial_bovespa')]),
        ),
        migrations.AlterUniqueTogether(
            name='proventoacaodescritodocumentobovespa',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='proventofiidescritodocumentobovespa',
            unique_together=set([]),
        ),
    ]
