# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-03 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0126_auto_20170203_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amortizacaodebenture',
            name='debenture',
        ),
        migrations.RemoveField(
            model_name='jurosdebenture',
            name='debenture',
        ),
        migrations.RemoveField(
            model_name='premiodebenture',
            name='debenture',
        ),
        migrations.DeleteModel(
            name='AmortizacaoDebenture',
        ),
        migrations.DeleteModel(
            name='JurosDebenture',
        ),
        migrations.DeleteModel(
            name='PremioDebenture',
        ),
    ]
