# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-08 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0128_amortizacaodebenture_jurosdebenture_premiodebenture'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historicofii',
            unique_together=set([('fii', 'data')]),
        ),
    ]
