# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-09 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0129_auto_20170208_0117'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historicotitulo',
            unique_together=set([('titulo', 'data')]),
        ),
    ]
