# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-11 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0131_auto_20170211_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='investidor',
            name='ultimo_acesso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\xdaltimo acesso a uma p\xe1gina'),
        ),
    ]
