# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-11 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0132_investidor_ultimo_acesso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investidor',
            name='ultimo_acesso',
        ),
        migrations.AddField(
            model_name='investidor',
            name='data_ultimo_acesso',
            field=models.DateField(blank=True, null=True, verbose_name='\xdaltimo dia de acesso a uma p\xe1gina'),
        ),
    ]
