# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-19 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0133_auto_20170211_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='fii',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bagogold.Empresa'),
        ),
    ]
