# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-19 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0134_fii_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoproventobovespa',
            name='protocolo',
            field=models.CharField(max_length=15, verbose_name='Protocolo'),
        ),
    ]
