# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-28 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0136_proventofii_tipo_provento'),
    ]

    operations = [
        migrations.AddField(
            model_name='proventofiidescritodocumentobovespa',
            name='tipo_provento',
            field=models.CharField(default='', max_length=1, verbose_name='Tipo de provento'),
            preserve_default=False,
        ),
    ]
