# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-28 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0137_proventofiidescritodocumentobovespa_tipo_provento'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proventofii',
            unique_together=set([('data_ex', 'data_pagamento', 'fii', 'valor_unitario', 'oficial_bovespa')]),
        ),
    ]
