# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-28 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0138_auto_20170228_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proventofii',
            name='url_documento',
        ),
    ]
