# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-11 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cri_cra', '0008_auto_20170311_0002'),
        ('bagogold', '0139_remove_proventofii_url_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisaoOperacaoCRI_CRA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=11, verbose_name=b'Quantidade (em certificados)')),
                ('divisao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Divisao')),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cri_cra.OperacaoCRI_CRA')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='divisaooperacaocri_cra',
            unique_together=set([('divisao', 'operacao')]),
        ),
    ]
