# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-12 13:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0140_auto_20170311_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacaodebenture',
            name='quantidade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade'),
        ),
    ]
