# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-21 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0141_auto_20170312_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisaooperacaoacao',
            name='quantidade',
            field=models.IntegerField(verbose_name=b'Quantidade'),
        ),
        migrations.AlterField(
            model_name='divisaooperacaocdb_rdb',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name=b'Quantidade'),
        ),
        migrations.AlterField(
            model_name='divisaooperacaocri_cra',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name=b'Quantidade'),
        ),
        migrations.AlterField(
            model_name='divisaooperacaodebenture',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name=b'Quantidade'),
        ),
        migrations.AlterField(
            model_name='divisaooperacaofii',
            name='quantidade',
            field=models.IntegerField(verbose_name=b'Quantidade'),
        ),
        migrations.AlterField(
            model_name='divisaooperacaofundoinvestimento',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name=b'Quantidade'),
        ),
        migrations.AlterField(
            model_name='divisaooperacaotd',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Quantidade'),
        ),
    ]
