# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-23 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0143_auto_20170321_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisaooperacaoacao',
            name='divisao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Divisao', verbose_name='Divis\xe3o'),
        ),
        migrations.AlterField(
            model_name='divisaooperacaocdb_rdb',
            name='divisao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Divisao', verbose_name='Divis\xe3o'),
        ),
        migrations.AlterField(
            model_name='divisaooperacaocri_cra',
            name='divisao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Divisao', verbose_name='Divis\xe3o'),
        ),
        migrations.AlterField(
            model_name='divisaooperacaodebenture',
            name='divisao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Divisao', verbose_name='Divis\xe3o'),
        ),
        migrations.AlterField(
            model_name='divisaooperacaofii',
            name='divisao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Divisao', verbose_name='Divis\xe3o'),
        ),
        migrations.AlterField(
            model_name='divisaooperacaofundoinvestimento',
            name='divisao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Divisao', verbose_name='Divis\xe3o'),
        ),
        migrations.AlterField(
            model_name='divisaooperacaolc',
            name='divisao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Divisao', verbose_name='Divis\xe3o'),
        ),
        migrations.AlterField(
            model_name='divisaooperacaotd',
            name='divisao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Divisao', verbose_name='Divis\xe3o'),
        ),
        migrations.AlterField(
            model_name='divisaoprincipal',
            name='divisao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Divisao', verbose_name='Divis\xe3o'),
        ),
        migrations.AlterField(
            model_name='transferenciaentredivisoes',
            name='divisao_cedente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='divisao_cedente', to='bagogold.Divisao', verbose_name='Divis\xe3o cedente'),
        ),
        migrations.AlterField(
            model_name='transferenciaentredivisoes',
            name='divisao_recebedora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='divisao_recebedora', to='bagogold.Divisao', verbose_name='Divis\xe3o recebedora'),
        ),
    ]
