# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-03 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0145_auto_20170429_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provento',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=18, max_digits=22, verbose_name='Valor unit\xe1rio'),
        ),
        migrations.AlterField(
            model_name='proventoacaodescritodocumentobovespa',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=18, max_digits=22, verbose_name='Valor unit\xe1rio'),
        ),
        migrations.AlterField(
            model_name='proventofii',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=18, max_digits=22, verbose_name='Valor unit\xe1rio'),
        ),
        migrations.AlterField(
            model_name='proventofiidescritodocumentobovespa',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=18, max_digits=22, verbose_name='Valor unit\xe1rio'),
        ),
    ]
