# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-04 04:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0146_auto_20170503_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionalidadeConstrucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Percentual feito')),
                ('tag', models.CharField(max_length=30, verbose_name='Tag da funcionalidade')),
            ],
        ),
    ]
