# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0148_loginincorreto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provento',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=16, max_digits=20, verbose_name='Valor unit\xe1rio'),
        ),
        migrations.AlterField(
            model_name='proventofii',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=16, max_digits=20, verbose_name='Valor unit\xe1rio'),
        ),
    ]
