# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0149_auto_20170608_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proventoacaodescritodocumentobovespa',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=16, max_digits=20, verbose_name='Valor unit\xe1rio'),
        ),
        migrations.AlterField(
            model_name='proventofiidescritodocumentobovespa',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=16, max_digits=20, verbose_name='Valor unit\xe1rio'),
        ),
    ]
