# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0153_atualizacaoselicprovento'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelicProventoAcaoDescritoDocBovespa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de \xednicio')),
                ('data_fim', models.DateField(verbose_name='Data de fim')),
                ('provento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Provento')),
            ],
        ),
    ]
