# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-03 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0154_selicproventoacaodescritodocbovespa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atualizacaoselicprovento',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de in\xedcio'),
        ),
        migrations.AlterField(
            model_name='selicproventoacaodescritodocbovespa',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de in\xedcio'),
        ),
        migrations.AlterField(
            model_name='selicproventoacaodescritodocbovespa',
            name='provento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bagogold.ProventoAcaoDescritoDocumentoBovespa'),
        ),
    ]
