# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-13 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0155_auto_20170903_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisaooperacaocdb_rdb',
            name='operacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdb_rdb.OperacaoCDB_RDB'),
        ),
    ]
