# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outros_investimentos', '0003_auto_20170915_2125'),
        ('bagogold', '0156_auto_20170913_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisaoInvestimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Divisao', verbose_name='Divis\xe3o')),
                ('investimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='outros_investimentos.Investimento')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='divisaoinvestimento',
            unique_together=set([('divisao', 'investimento')]),
        ),
    ]
