# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0157_auto_20170916_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisaoinvestimento',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name=b'Quantidade'),
            preserve_default=False,
        ),
    ]
