# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-10 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0160_auto_20171021_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoLeitura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do pagamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor pago')),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Investidor')),
            ],
        ),
    ]
