# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-16 00:19
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0161_pagamentoleitura'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAgrupamentoFII',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('proporcao', models.DecimalField(decimal_places=12, max_digits=13, validators=[django.core.validators.MaxValueValidator(Decimal('0.999999999999'))], verbose_name='Propor\xe7\xe3o de agrupamento')),
                ('valor_fracao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Valor para as fra\xe7\xf5es')),
            ],
        ),
        migrations.CreateModel(
            name='EventoDesdobramentoFII',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('proporcao', models.DecimalField(decimal_places=12, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('1.000000000001'))], verbose_name='Propor\xe7\xe3o de desdobramento')),
                ('valor_fracao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Valor para as fra\xe7\xf5es')),
            ],
        ),
        migrations.CreateModel(
            name='EventoIncorporacaoFII',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
            ],
        ),
        migrations.AddField(
            model_name='fii',
            name='encerrado',
            field=models.BooleanField(default=False, verbose_name='FII encerrado?'),
        ),
        migrations.AddField(
            model_name='eventoincorporacaofii',
            name='fii',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.FII'),
        ),
        migrations.AddField(
            model_name='eventoincorporacaofii',
            name='novo_fii',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incorporacao', to='bagogold.FII'),
        ),
        migrations.AddField(
            model_name='eventodesdobramentofii',
            name='fii',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.FII'),
        ),
        migrations.AddField(
            model_name='eventoagrupamentofii',
            name='fii',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.FII'),
        ),
        migrations.AlterUniqueTogether(
            name='eventoincorporacaofii',
            unique_together=set([('fii', 'data')]),
        ),
        migrations.AlterUniqueTogether(
            name='eventodesdobramentofii',
            unique_together=set([('fii', 'data')]),
        ),
        migrations.AlterUniqueTogether(
            name='eventoagrupamentofii',
            unique_together=set([('fii', 'data')]),
        ),
    ]
