# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-15 19:18
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0161_pagamentoleitura'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoFII',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='EventoAgrupamentoFII',
            fields=[
                ('eventofii_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bagogold.EventoFII')),
                ('proporcao', models.DecimalField(decimal_places=12, max_digits=13, validators=[django.core.validators.MaxValueValidator(Decimal('0.999999999999'))], verbose_name='Propor\xe7\xe3o de agrupamento')),
            ],
            bases=('bagogold.eventofii',),
        ),
        migrations.CreateModel(
            name='EventoDesdobramentoFII',
            fields=[
                ('eventofii_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bagogold.EventoFII')),
                ('proporcao', models.DecimalField(decimal_places=12, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('1.000000000001'))], verbose_name='Propor\xe7\xe3o de desdobramento')),
            ],
            bases=('bagogold.eventofii',),
        ),
        migrations.CreateModel(
            name='EventoIncorporacaoFII',
            fields=[
                ('eventofii_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bagogold.EventoFII')),
                ('novo_fii', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.FII')),
            ],
            bases=('bagogold.eventofii',),
        ),
        migrations.AddField(
            model_name='eventofii',
            name='fii',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.FII'),
        ),
    ]
