# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-15 23:02
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0162_auto_20171115_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoagrupamentofii',
            name='valor_fracao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Valor para as fra\xe7\xf5es'),
        ),
        migrations.AddField(
            model_name='eventodesdobramentofii',
            name='valor_fracao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Valor para as fra\xe7\xf5es'),
        ),
    ]
