# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-17 15:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0162_auto_20171115_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckpointFII',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField(verbose_name='Ano')),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade no ano')),
                ('fii', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.FII')),
            ],
        ),
        migrations.CreateModel(
            name='CheckpointProventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField(verbose_name='Ano')),
                ('valor', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='Valor da poupan\xe7a de proventos')),
            ],
        ),
    ]
