# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-17 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0163_checkpointfii_checkpointproventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointfii',
            name='preco_medio',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=11, verbose_name='Pre\xe7o m\xe9dio'),
            preserve_default=False,
        ),
    ]
