# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-17 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0164_checkpointfii_preco_medio'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointfii',
            name='investidor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bagogold.Investidor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkpointproventos',
            name='investidor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bagogold.Investidor'),
            preserve_default=False,
        ),
    ]
