# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-19 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0165_auto_20171117_1312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckpointProventos',
            new_name='CheckpointProventosFII',
        ),
        migrations.AlterUniqueTogether(
            name='checkpointfii',
            unique_together=set([('fii', 'ano', 'investidor')]),
        ),
        migrations.AlterUniqueTogether(
            name='checkpointproventosfii',
            unique_together=set([('ano', 'investidor')]),
        ),
    ]
