# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-26 22:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0167_auto_20171123_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacaofii',
            name='quantidade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade'),
        ),
    ]
