# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-14 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0171_auto_20180219_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointdivisaocdb_rdb',
            name='divisao_operacao',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bagogold.DivisaoOperacaoCDB_RDB'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='checkpointdivisaocdb_rdb',
            unique_together=set([('divisao_operacao', 'ano')]),
        ),
    ]
