# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-14 06:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0172_auto_20180314_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpointdivisaocdb_rdb',
            name='divisao',
        ),
        migrations.RemoveField(
            model_name='checkpointdivisaocdb_rdb',
            name='operacao',
        ),
    ]
