# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-22 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0174_checkpointdivisaoletracambio_divisaooperacaoletracambio'),
        ('lc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisaooperacaoletracambio',
            name='operacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lc.OperacaoLetraCambio'),
        ),
        migrations.AddField(
            model_name='checkpointdivisaoletracambio',
            name='divisao_operacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.DivisaoOperacaoLetraCambio'),
        ),
        migrations.AlterUniqueTogether(
            name='divisaooperacaoletracambio',
            unique_together=set([('divisao', 'operacao')]),
        ),
        migrations.AlterUniqueTogether(
            name='checkpointdivisaoletracambio',
            unique_together=set([('divisao_operacao', 'ano')]),
        ),
    ]
