# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-22 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0175_auto_20180322_1511'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DivisaoOperacaoLC',
            new_name='DivisaoOperacaoLCI_LCA',
        ),
    ]
