# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-23 00:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0177_auto_20180417_0424'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkpointfii',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='checkpointfii',
            name='fii',
        ),
        migrations.RemoveField(
            model_name='checkpointfii',
            name='investidor',
        ),
        migrations.AlterUniqueTogether(
            name='checkpointproventosfii',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='checkpointproventosfii',
            name='investidor',
        ),
        migrations.AlterUniqueTogether(
            name='eventoagrupamentofii',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='eventoagrupamentofii',
            name='fii',
        ),
        migrations.AlterUniqueTogether(
            name='eventodesdobramentofii',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='eventodesdobramentofii',
            name='fii',
        ),
        migrations.AlterUniqueTogether(
            name='eventoincorporacaofii',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='eventoincorporacaofii',
            name='fii',
        ),
        migrations.RemoveField(
            model_name='eventoincorporacaofii',
            name='novo_fii',
        ),
        migrations.RemoveField(
            model_name='fii',
            name='empresa',
        ),
        migrations.AlterUniqueTogether(
            name='historicofii',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='historicofii',
            name='fii',
        ),
        migrations.RemoveField(
            model_name='operacaofii',
            name='fii',
        ),
        migrations.RemoveField(
            model_name='operacaofii',
            name='investidor',
        ),
        migrations.AlterUniqueTogether(
            name='proventofii',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='proventofii',
            name='fii',
        ),
        migrations.RemoveField(
            model_name='usoproventosoperacaofii',
            name='divisao_operacao',
        ),
        migrations.RemoveField(
            model_name='usoproventosoperacaofii',
            name='operacao',
        ),
        migrations.RemoveField(
            model_name='valordiariofii',
            name='fii',
        ),
        migrations.DeleteModel(
            name='CheckpointFII',
        ),
        migrations.DeleteModel(
            name='CheckpointProventosFII',
        ),
        migrations.DeleteModel(
            name='EventoAgrupamentoFII',
        ),
        migrations.DeleteModel(
            name='EventoDesdobramentoFII',
        ),
        migrations.DeleteModel(
            name='EventoIncorporacaoFII',
        ),
        migrations.DeleteModel(
            name='FII',
        ),
        migrations.DeleteModel(
            name='HistoricoFII',
        ),
        migrations.DeleteModel(
            name='OperacaoFII',
        ),
        migrations.DeleteModel(
            name='ProventoFII',
        ),
        migrations.DeleteModel(
            name='UsoProventosOperacaoFII',
        ),
        migrations.DeleteModel(
            name='ValorDiarioFII',
        ),
    ]
