# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-24 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pendencias', '0005_auto_20180424_0152'),
        ('bagogold', '0179_auto_20180424_0143'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historicotitulo',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='historicotitulo',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='operacaotitulo',
            name='investidor',
        ),
        migrations.RemoveField(
            model_name='operacaotitulo',
            name='titulo',
        ),
        migrations.DeleteModel(
            name='Titulo',
        ),
        migrations.RemoveField(
            model_name='valordiariotitulo',
            name='titulo',
        ),
        migrations.DeleteModel(
            name='HistoricoTitulo',
        ),
        migrations.DeleteModel(
            name='OperacaoTitulo',
        ),
        migrations.DeleteModel(
            name='ValorDiarioTitulo',
        ),
    ]
