# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-12 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0182_auto_20180429_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoipca',
            name='valor',
            field=models.DecimalField(decimal_places=9, max_digits=12, verbose_name='Valor IPCA'),
        ),
    ]
