# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-13 22:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0183_auto_20180512_0456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicoipca',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='historicoipca',
            name='mes',
        ),
        migrations.AddField(
            model_name='historicoipca',
            name='data_inicio',
            field=models.DateField(default=datetime.date(2018, 5, 13), verbose_name='Data de in\xedcio'),
            preserve_default=False,
        ),
    ]
