# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-13 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0184_auto_20180513_1955'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historicoipca',
            unique_together=set([('data_inicio',)]),
        ),
    ]
