# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-14 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0185_auto_20180513_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPCAProjetado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bagogold.HistoricoIPCA')),
            ],
        ),
    ]
