# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-14 01:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0186_ipcaprojetado'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoipca',
            name='data_fim',
            field=models.DateField(default=datetime.date(2018, 5, 13), verbose_name='Data de fim'),
            preserve_default=False,
        ),
    ]
