# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-14 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0187_historicoipca_data_fim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacaodebenture',
            name='investidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op_debenture_antigo', to='bagogold.Investidor'),
        ),
    ]
