# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-24 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0188_auto_20180513_2355'),
        ('debentures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisaooperacaodebenture',
            name='operacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debentures.OperacaoDebenture'),
        ),
    ]
