# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-25 18:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0189_auto_20180524_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoInvestidorLeituraDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=15, verbose_name='Protocolo do documento')),
                ('decisao', models.CharField(max_length=1, verbose_name='Decis\xe3o')),
                ('data_leitura', models.DateTimeField(verbose_name='Data da leitura')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Empresa')),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras_apagadas', to='bagogold.Investidor')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoInvestidorRecusaDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=15, verbose_name='Protocolo do documento')),
                ('motivo', models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Motivo da recusa')),
                ('data_recusa', models.DateTimeField(verbose_name='Data da recusa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Empresa')),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras_apagadas_que_recusou', to='bagogold.Investidor')),
                ('responsavel_leitura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras_apagadas_recusadas', to='bagogold.Investidor')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoInvestidorValidacaoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=15, verbose_name='Protocolo do documento')),
                ('data_validacao', models.DateTimeField(verbose_name='Data da valida\xe7\xe3o')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Empresa')),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validacoes_apagadas', to='bagogold.Investidor')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='historicoinvestidorvalidacaodocumento',
            unique_together=set([('empresa', 'investidor', 'protocolo')]),
        ),
        migrations.AlterUniqueTogether(
            name='historicoinvestidorleituradocumento',
            unique_together=set([('empresa', 'investidor', 'protocolo')]),
        ),
    ]
