# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-26 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0190_auto_20180825_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoinvestidorleituradocumento',
            name='tipo_investimento',
            field=models.CharField(default='F', max_length=1, verbose_name='Tipo de investimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicoinvestidorrecusadocumento',
            name='tipo_investimento',
            field=models.CharField(default='F', max_length=1, verbose_name='Tipo de investimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicoinvestidorvalidacaodocumento',
            name='tipo_investimento',
            field=models.CharField(default='F', max_length=1, verbose_name='Tipo de investimento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentoproventobovespa',
            name='tipo',
            field=models.CharField(max_length=1, verbose_name='Tipo de investimento'),
        ),
    ]
