# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-13 15:39
from __future__ import unicode_literals

import bagogold.bagogold.models.gerador_proventos
import bagogold.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0192_historicoinvestidorleituradocumento_proventos_criados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoproventobovespa',
            name='documento',
            field=models.FileField(blank=True, null=True, storage=bagogold.storage_backends.MediaStorage(), upload_to=bagogold.bagogold.models.gerador_proventos.ticker_path),
        ),
    ]
