# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-30 02:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0193_auto_20181013_1539'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historicotaxadi',
            unique_together=set([('data',)]),
        ),
    ]
