# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-08 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0194_auto_20181029_2341'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historicotaxaselic',
            unique_together=set([('data',)]),
        ),
    ]
