# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-07 03:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0005_auto_20190307_0009'),
        ('bagogold', '0194_auto_20181029_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckpointDivisaoAcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField(verbose_name='Ano')),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade no ano')),
                ('preco_medio', models.DecimalField(decimal_places=4, max_digits=11, verbose_name='Pre\xe7o m\xe9dio')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acoes.Acao')),
                ('divisao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Divisao', verbose_name='Divis\xe3o')),
            ],
        ),
        migrations.CreateModel(
            name='CheckpointDivisaoProventosAcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField(verbose_name='Ano')),
                ('valor', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='Valor da poupan\xe7a de proventos')),
                ('divisao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Divisao', verbose_name='Divis\xe3o')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='checkpointdivisaoproventosacao',
            unique_together=set([('ano', 'divisao')]),
        ),
        migrations.AlterUniqueTogether(
            name='checkpointdivisaoacao',
            unique_together=set([('acao', 'ano', 'divisao')]),
        ),
    ]
