# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-03 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bagogold', '0176_auto_20180322_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoTitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('taxa_compra', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taxa de compra')),
                ('taxa_venda', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taxa de venda')),
                ('preco_compra', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Pre\xe7o de compra')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Pre\xe7o de venda')),
            ],
        ),
        migrations.CreateModel(
            name='OperacaoTitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Pre\xe7o unit\xe1rio')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Quantidade')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('taxa_bvmf', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Taxa BVMF')),
                ('taxa_custodia', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Taxa do agente de cust\xf3dia')),
                ('tipo_operacao', models.CharField(max_length=1, verbose_name='Tipo de opera\xe7\xe3o')),
                ('consolidada', models.NullBooleanField(verbose_name='Consolidada?')),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tesouro_direto_novo', to='bagogold.Investidor')),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, unique_for_date=b'data_vencimento', verbose_name='Tipo do t\xedtulo')),
                ('data_vencimento', models.DateField(verbose_name='Data de vencimento')),
                ('data_inicio', models.DateField(verbose_name='Data de in\xedcio')),
            ],
        ),
        migrations.CreateModel(
            name='ValorDiarioTitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Hor\xe1rio')),
                ('taxa_compra', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taxa de compra')),
                ('taxa_venda', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taxa de venda')),
                ('preco_compra', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Pre\xe7o de compra')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Pre\xe7o de venda')),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesouro_direto.Titulo')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='titulo',
            unique_together=set([('tipo', 'data_vencimento')]),
        ),
        migrations.AddField(
            model_name='operacaotitulo',
            name='titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesouro_direto.Titulo'),
        ),
        migrations.AddField(
            model_name='historicotitulo',
            name='titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesouro_direto.Titulo', unique_for_date=b'data'),
        ),
        migrations.AlterUniqueTogether(
            name='historicotitulo',
            unique_together=set([('titulo', 'data')]),
        ),
    ]
