# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-28 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lci_lca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoVencimentoLetraCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vencimento', models.IntegerField(verbose_name='Per\xedodo de vencimento')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data da varia\xe7\xe3o')),
                ('letra_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lci_lca.LetraCredito')),
            ],
        ),
    ]
