# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-24 04:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lci_lca', '0003_auto_20180424_0158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckpointCDB_RDB',
            new_name='CheckpointLetraCredito',
        ),
    ]
