# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-24 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lci_lca', '0004_auto_20180424_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='letracredito',
            name='tipo_rendimento',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Tipo de rendimento'),
            preserve_default=False,
        ),
    ]
