# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-07 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bagogold', '0139_remove_proventofii_url_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRI_CRA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='C\xf3digo')),
                ('tipo', models.CharField(choices=[(b'I', b'CRI'), (b'A', b'CRA')], max_length=1, verbose_name='Tipo')),
                ('tipo_indexacao', models.PositiveSmallIntegerField(verbose_name='Tipo de indexa\xe7\xe3o')),
                ('porcentagem', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Porcentagem sobre indexa\xe7\xe3o')),
                ('juros_adicional', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Juros adicional')),
                ('data_emissao', models.DateField(verbose_name='Data de emiss\xe3o')),
                ('valor_emissao', models.DecimalField(decimal_places=8, max_digits=15, verbose_name='Valor nominal na emiss\xe3o')),
                ('data_vencimento', models.DateField(verbose_name='Data de vencimento')),
            ],
        ),
        migrations.CreateModel(
            name='OperacaoCRI_CRA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Pre\xe7o unit\xe1rio')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('data', models.DateField(verbose_name='Data da opera\xe7\xe3o')),
                ('tipo_operacao', models.CharField(max_length=1, verbose_name='Tipo de opera\xe7\xe3o')),
                ('cri_cra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cri_cra.CRI_CRA')),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Investidor')),
            ],
        ),
    ]
