# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-08 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0139_remove_proventofii_url_documento'),
        ('cri_cra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAmortizacaoCRI_CRA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data de remunera\xe7\xe3o')),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Percentual de amortiza\xe7\xe3o')),
            ],
        ),
        migrations.CreateModel(
            name='DataRemuneracaoCRI_CRA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data de remunera\xe7\xe3o')),
            ],
        ),
        migrations.RemoveField(
            model_name='operacaocri_cra',
            name='investidor',
        ),
        migrations.AddField(
            model_name='cri_cra',
            name='investidor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bagogold.Investidor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cri_cra',
            name='nome',
            field=models.CharField(default='Teste', max_length=50, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cri_cra',
            name='tipo_indexacao',
            field=models.PositiveSmallIntegerField(choices=[(1, b'DI'), (2, b'Prefixado'), (3, b'IPCA'), (4, b'Selic'), (5, b'IGP-M')], verbose_name='Tipo de indexa\xe7\xe3o'),
        ),
        migrations.AddField(
            model_name='dataremuneracaocri_cra',
            name='cri_cra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cri_cra.CRI_CRA'),
        ),
        migrations.AddField(
            model_name='dataamortizacaocri_cra',
            name='cri_cra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cri_cra.CRI_CRA'),
        ),
        migrations.AlterUniqueTogether(
            name='dataremuneracaocri_cra',
            unique_together=set([('data', 'cri_cra')]),
        ),
        migrations.AlterUniqueTogether(
            name='dataamortizacaocri_cra',
            unique_together=set([('data', 'cri_cra')]),
        ),
    ]
