# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-08 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cri_cra', '0002_auto_20170307_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cri_cra',
            name='codigo',
        ),
        migrations.AddField(
            model_name='cri_cra',
            name='codigo_isin',
            field=models.CharField(default='', max_length=20, verbose_name='C\xf3digo ISIN'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cri_cra',
            name='juros_adicional',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Juros adicional'),
        ),
    ]
