# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-09 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cri_cra', '0003_auto_20170307_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataamortizacaocri_cra',
            old_name='quantidade',
            new_name='percentual',
        ),
        migrations.AlterField(
            model_name='dataamortizacaocri_cra',
            name='data',
            field=models.DateField(verbose_name='Data de amortiza\xe7\xe3o'),
        ),
    ]
