# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-09 14:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cri_cra', '0006_auto_20170309_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataamortizacaocri_cra',
            name='percentual',
            field=models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Percentual de amortiza\xe7\xe3o'),
        ),
    ]
