# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-11 03:02
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cri_cra', '0007_auto_20170309_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataamortizacaocri_cra',
            name='percentual',
            field=models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Percentual de amortiza\xe7\xe3o'),
        ),
        migrations.AlterUniqueTogether(
            name='cri_cra',
            unique_together=set([('investidor', 'codigo_isin')]),
        ),
    ]
