# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-12 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cri_cra', '0008_auto_20170311_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacaocri_cra',
            name='taxa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Taxa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operacaocri_cra',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data da opera\xe7\xe3o'),
        ),
    ]
