# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-12 14:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cri_cra', '0010_auto_20170312_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacaocri_cra',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 3, 12, 14, 28, 40, 933798, tzinfo=utc), verbose_name='Data da opera\xe7\xe3o'),
            preserve_default=False,
        ),
    ]
