# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-09 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bagogold', '0155_auto_20170903_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDB_RDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('tipo', models.CharField(max_length=1, verbose_name='Tipo')),
                ('tipo_rendimento', models.PositiveSmallIntegerField(verbose_name='Tipo de rendimento')),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdb_rdb_novo', to='bagogold.Investidor')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoCarenciaCDB_RDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carencia', models.IntegerField(verbose_name='Per\xedodo de car\xeancia')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data da varia\xe7\xe3o')),
                ('cdb_rdb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdb_rdb.CDB_RDB')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoPorcentagemCDB_RDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentagem', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentagem de rendimento')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data da varia\xe7\xe3o')),
                ('cdb_rdb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdb_rdb.CDB_RDB')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoValorMinimoInvestimentoCDB_RDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_minimo', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor m\xednimo para investimento')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data da varia\xe7\xe3o')),
                ('cdb_rdb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdb_rdb.CDB_RDB')),
            ],
        ),
        migrations.CreateModel(
            name='OperacaoCDB_RDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Quantidade investida/resgatada')),
                ('data', models.DateField(verbose_name='Data da opera\xe7\xe3o')),
                ('tipo_operacao', models.CharField(max_length=1, verbose_name='Tipo de opera\xe7\xe3o')),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op_cdb_rdb_novo', to='bagogold.Investidor')),
                ('investimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdb_rdb.CDB_RDB')),
            ],
        ),
        migrations.CreateModel(
            name='OperacaoVendaCDB_RDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacao_compra', to='cdb_rdb.OperacaoCDB_RDB')),
                ('operacao_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacao_venda', to='cdb_rdb.OperacaoCDB_RDB')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='operacaovendacdb_rdb',
            unique_together=set([('operacao_compra', 'operacao_venda')]),
        ),
    ]
