# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-09 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdb_rdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoVencimentoCDB_RDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vencimento', models.IntegerField(verbose_name='Per\xedodo de vencimento')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data da varia\xe7\xe3o')),
                ('cdb_rdb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdb_rdb.CDB_RDB')),
            ],
        ),
    ]
