# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-18 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdb_rdb', '0003_auto_20180217_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpointcdb_rdb',
            name='investidor',
        ),
        migrations.AlterUniqueTogether(
            name='checkpointcdb_rdb',
            unique_together=set([('operacao', 'ano')]),
        ),
    ]
