# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-06 03:51
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bagogold', '0194_auto_20181029_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, verbose_name='Ticker da a\xe7\xe3o')),
                ('tipo', models.CharField(max_length=5, verbose_name='Tipo de a\xe7\xe3o')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acao_novo', to='bagogold.Empresa')),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='AcaoProvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento_frac', models.DateField(blank=True, null=True, verbose_name='Data do pagamento de fra\xe7\xf5es')),
                ('valor_calculo_frac', models.DecimalField(decimal_places=10, default=0, max_digits=14, verbose_name='Valor para c\xe1lculo das fra\xe7\xf5es')),
                ('acao_recebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acoes.Acao', verbose_name=b'A\xc3\xa7\xc3\xa3o')),
            ],
        ),
        migrations.CreateModel(
            name='AtualizacaoSelicProvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_rendimento', models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True, verbose_name='Valor do rendimento')),
                ('data_inicio', models.DateField(verbose_name='Data de in\xedcio')),
                ('data_fim', models.DateField(verbose_name='Data de fim')),
            ],
        ),
        migrations.CreateModel(
            name='CheckpointAcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField(verbose_name='Ano')),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade no ano')),
                ('preco_medio', models.DecimalField(decimal_places=4, max_digits=11, verbose_name='Pre\xe7o m\xe9dio')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acoes.Acao')),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Investidor')),
            ],
        ),
        migrations.CreateModel(
            name='CheckpointProventosAcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField(verbose_name='Ano')),
                ('valor', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='Valor da poupan\xe7a de proventos')),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Investidor')),
            ],
        ),
        migrations.CreateModel(
            name='EventoAgrupamentoAcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('proporcao', models.DecimalField(decimal_places=12, max_digits=13, validators=[django.core.validators.MaxValueValidator(Decimal('0.999999999999'))], verbose_name='Propor\xe7\xe3o de agrupamento')),
                ('valor_fracao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Valor para as fra\xe7\xf5es')),
                ('data_pgto_fracao', models.DateField(blank=True, null=True, verbose_name='Data de pagamento para as fra\xe7\xf5es')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acoes.Acao')),
            ],
        ),
        migrations.CreateModel(
            name='EventoAlteracaoAcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acoes.Acao')),
                ('nova_acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alteracao', to='acoes.Acao')),
            ],
        ),
        migrations.CreateModel(
            name='EventoBonusAcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('proporcao', models.DecimalField(decimal_places=12, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('1.000000000001'))], verbose_name='Propor\xe7\xe3o de desdobramento')),
                ('valor_fracao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Valor para as fra\xe7\xf5es')),
                ('data_pgto_fracao', models.DateField(blank=True, null=True, verbose_name='Data de pagamento para as fra\xe7\xf5es')),
                ('preco_unitario_acao', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Pre\xe7o unit\xe1rio por a\xe7\xe3o')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acoes.Acao')),
            ],
        ),
        migrations.CreateModel(
            name='EventoDesdobramentoAcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('proporcao', models.DecimalField(decimal_places=12, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('1.000000000001'))], verbose_name='Propor\xe7\xe3o de desdobramento')),
                ('valor_fracao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Valor para as fra\xe7\xf5es')),
                ('data_pgto_fracao', models.DateField(blank=True, null=True, verbose_name='Data de pagamento para as fra\xe7\xf5es')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acoes.Acao')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoAcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Pre\xe7o unit\xe1rio')),
                ('oficial_bovespa', models.BooleanField(default=False, verbose_name='Oficial Bovespa?')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acoes.Acao', unique_for_date=b'data', verbose_name=b'A\xc3\xa7\xc3\xa3o')),
            ],
        ),
        migrations.CreateModel(
            name='OperacaoAcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Pre\xe7o unit\xe1rio')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('corretagem', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Corretagem')),
                ('emolumentos', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Emolumentos')),
                ('tipo_operacao', models.CharField(max_length=1, verbose_name='Tipo de opera\xe7\xe3o')),
                ('consolidada', models.NullBooleanField(verbose_name='Consolidada?')),
                ('destinacao', models.CharField(max_length=1, verbose_name='Destina\xe7\xe3o')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acoes.Acao', verbose_name=b'A\xc3\xa7\xc3\xa3o')),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op_acao_novo', to='bagogold.Investidor')),
            ],
        ),
        migrations.CreateModel(
            name='OperacaoCompraVenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_trade', models.NullBooleanField(verbose_name='\xc9 day trade?')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade de a\xe7\xf5es')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compra', to='acoes.OperacaoAcao', verbose_name=b'Compra')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venda', to='acoes.OperacaoAcao', verbose_name=b'Venda')),
            ],
        ),
        migrations.CreateModel(
            name='ProventoAcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_unitario', models.DecimalField(decimal_places=16, max_digits=20, verbose_name='Valor unit\xe1rio')),
                ('tipo_provento', models.CharField(max_length=1, verbose_name='Tipo de provento')),
                ('data_ex', models.DateField(verbose_name='Data EX')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('observacao', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observa\xe7\xe3o')),
                ('oficial_bovespa', models.BooleanField(default=False, verbose_name='Oficial Bovespa?')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acoes.Acao', verbose_name=b'A\xc3\xa7\xc3\xa3o')),
            ],
        ),
        migrations.CreateModel(
            name='TaxaCustodiaAcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Valor mensal')),
                ('ano_vigencia', models.IntegerField(verbose_name='Ano de in\xedcio de vig\xeancia')),
                ('mes_vigencia', models.IntegerField(verbose_name='M\xeas de in\xedcio de vig\xeancia')),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tx_custodia_novo', to='bagogold.Investidor')),
            ],
        ),
        migrations.CreateModel(
            name='UsoProventosOperacaoAcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_utilizada', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Quantidade de proventos utilizada')),
                ('divisao_operacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uso_prov_op_acao_novo', to='bagogold.DivisaoOperacaoAcao')),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acoes.OperacaoAcao', verbose_name=b'Opera\xc3\xa7\xc3\xa3o')),
            ],
        ),
        migrations.CreateModel(
            name='ValorDiarioAcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Hor\xe1rio')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Pre\xe7o unit\xe1rio')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acoes.Acao', verbose_name=b'A\xc3\xa7\xc3\xa3o')),
            ],
        ),
        migrations.AddField(
            model_name='atualizacaoselicprovento',
            name='provento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='acoes.ProventoAcao'),
        ),
        migrations.AddField(
            model_name='acaoprovento',
            name='provento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acoes.ProventoAcao'),
        ),
        migrations.AlterUniqueTogether(
            name='proventoacao',
            unique_together=set([('acao', 'valor_unitario', 'data_ex', 'data_pagamento', 'tipo_provento', 'oficial_bovespa')]),
        ),
        migrations.AlterUniqueTogether(
            name='operacaocompravenda',
            unique_together=set([('compra', 'venda')]),
        ),
        migrations.AlterUniqueTogether(
            name='historicoacao',
            unique_together=set([('acao', 'data')]),
        ),
        migrations.AlterUniqueTogether(
            name='eventodesdobramentoacao',
            unique_together=set([('acao', 'data')]),
        ),
        migrations.AlterUniqueTogether(
            name='eventobonusacao',
            unique_together=set([('acao', 'data')]),
        ),
        migrations.AlterUniqueTogether(
            name='eventoalteracaoacao',
            unique_together=set([('acao',)]),
        ),
        migrations.AlterUniqueTogether(
            name='eventoagrupamentoacao',
            unique_together=set([('acao', 'data')]),
        ),
        migrations.AlterUniqueTogether(
            name='checkpointproventosacao',
            unique_together=set([('ano', 'investidor')]),
        ),
        migrations.AlterUniqueTogether(
            name='checkpointacao',
            unique_together=set([('acao', 'ano', 'investidor')]),
        ),
        migrations.AlterUniqueTogether(
            name='acao',
            unique_together=set([('ticker', 'empresa', 'tipo')]),
        ),
    ]
