# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-06 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacaoacao',
            name='destinacao',
            field=models.CharField(choices=[(b'B', b'Buy and Hold'), (b'T', b'Trading')], max_length=1, verbose_name='Destina\xe7\xe3o'),
        ),
    ]
