# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-06 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0002_auto_20190306_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacaoacao',
            name='destinacao',
            field=models.SmallIntegerField(choices=[(1, b'Buy and Hold'), (2, b'Trading')], verbose_name='Destina\xe7\xe3o'),
        ),
    ]
