# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-06 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0003_auto_20190306_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoBonusAcaoRecebida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao_recebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acoes.Acao')),
                ('bonus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='acoes.EventoBonusAcao')),
            ],
        ),
    ]
