# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-07 03:09
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0004_eventobonusacaorecebida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventobonusacao',
            name='proporcao',
            field=models.DecimalField(decimal_places=12, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('1E-12'))], verbose_name='Propor\xe7\xe3o de desdobramento'),
        ),
        migrations.AlterField(
            model_name='proventoacao',
            name='tipo_provento',
            field=models.SmallIntegerField(max_length=1, verbose_name='Tipo de provento'),
        ),
    ]
