# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-08 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0006_auto_20190307_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointacao',
            name='destinacao',
            field=models.SmallIntegerField(choices=[(1, b'Buy and Hold'), (2, b'Trading')], default=1, verbose_name='Destina\xe7\xe3o'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkpointproventosacao',
            name='destinacao',
            field=models.SmallIntegerField(choices=[(1, b'Buy and Hold'), (2, b'Trading')], default=1, verbose_name='Destina\xe7\xe3o'),
            preserve_default=False,
        ),
    ]
