# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-08 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0195_auto_20190307_0009'),
        ('acoes', '0007_auto_20190307_2150'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkpointacao',
            unique_together=set([('acao', 'ano', 'investidor', 'destinacao')]),
        ),
        migrations.AlterUniqueTogether(
            name='checkpointproventosacao',
            unique_together=set([('ano', 'investidor', 'destinacao')]),
        ),
    ]
