# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-10 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bagogold', '0130_auto_20170208_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendenciaVencimentoTesouroDireto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Quantidade')),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Titulo')),
            ],
        ),
    ]
