# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-10 15:54
from __future__ import unicode_literals
from django.db import migrations, models
from django.utils import timezone
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0130_auto_20170208_2334'),
        ('pendencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendenciavencimentotesourodireto',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now(), verbose_name='Data de cria\xe7\xe3o'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendenciavencimentotesourodireto',
            name='investidor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bagogold.Investidor'),
            preserve_default=False,
        ),
    ]
