# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-11 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pendencias', '0002_auto_20170210_1354'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pendenciavencimentotesourodireto',
            unique_together=set([('titulo', 'investidor')]),
        ),
    ]
