# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-03 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagogold', '0139_remove_proventofii_url_documento'),
        ('pendencias', '0003_auto_20170211_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendenciaDocumentoGeradorProventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de cria\xe7\xe3o')),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagogold.Investidor')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pendenciadocumentogeradorproventos',
            unique_together=set([('investidor',)]),
        ),
    ]
