# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bagogold', '0148_loginincorreto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=20, verbose_name='CNPJ')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoCadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField(verbose_name='Data de refer\xeancia')),
                ('data_pedido_cvm', models.DateField(verbose_name='Data de pedido \xe0 CVM')),
                ('leitura_realizada', models.BooleanField(default=False, verbose_name='Leitura realizada')),
            ],
        ),
        migrations.CreateModel(
            name='FundoInvestimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=20, verbose_name='CNPJ')),
                ('data_constituicao', models.DateField(verbose_name=b'Data de constitui\xc3\xa7\xc3\xa3o')),
                ('situacao', models.PositiveSmallIntegerField(choices=[(1, 'Em funcionamento normal'), (2, 'Fase pr\xe9-operacional'), (3, 'Terminado')], verbose_name='Situa\xe7\xe3o')),
                ('tipo_prazo', models.CharField(choices=[(b'C', b'Curto'), (b'L', b'Longo')], max_length=1, verbose_name='Tipo de prazo')),
                ('classe', models.PositiveSmallIntegerField(choices=[(1, 'Fundo de A\xe7\xf5es'), (2, 'Fundo de Renda Fixa'), (3, 'Fundo Multimercado'), (4, 'Fundo Referenciado'), (5, 'Fundo da D\xedvida Externa'), (6, 'Fundo Cambial'), (7, 'Fundo de Curto Prazo')], verbose_name='Classe')),
                ('exclusivo_qualificados', models.BooleanField(verbose_name='Exclusivo para investidores qualificados?')),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundo_investimento.Administrador')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoValorCotas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('valor_cota', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Valor da cota')),
                ('fundo_investimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundo_investimento.FundoInvestimento')),
            ],
        ),
        migrations.CreateModel(
            name='LinkDocumentoCadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL do documento de cadastro')),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fundo_investimento.DocumentoCadastro')),
            ],
        ),
        migrations.CreateModel(
            name='OperacaoFundoInvestimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Quantidade de cotas')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Valor da opera\xe7\xe3o')),
                ('data', models.DateField(verbose_name='Data da opera\xe7\xe3o')),
                ('tipo_operacao', models.CharField(max_length=1, verbose_name='Tipo de opera\xe7\xe3o')),
                ('fundo_investimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundo_investimento.FundoInvestimento')),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundo_investimento', to='bagogold.Investidor')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='documentocadastro',
            unique_together=set([('data_referencia',)]),
        ),
        migrations.AlterUniqueTogether(
            name='administrador',
            unique_together=set([('cnpj',)]),
        ),
        migrations.AlterUniqueTogether(
            name='fundoinvestimento',
            unique_together=set([('cnpj',)]),
        ),
    ]
