# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 03:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundo_investimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundoinvestimento',
            name='ultimo_registro',
            field=models.DateField(default=datetime.date(2017, 5, 31), verbose_name='\xdaltimo registro'),
            preserve_default=False,
        ),
    ]
