# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 03:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundo_investimento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundoinvestimento',
            name='data_inicio',
        ),
        migrations.AddField(
            model_name='fundoinvestimento',
            name='data_constituicao',
            field=models.DateField(default=datetime.date(2017, 5, 29), verbose_name=b'Data de constitui\xc3\xa7\xc3\xa3o'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='administrador',
            unique_together=set([('cnpj',)]),
        ),
    ]
