# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundo_investimento', '0002_fundoinvestimento_ultimo_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundoinvestimento',
            name='classe',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Indefinida'), (1, 'Fundo de A\xe7\xf5es'), (2, 'Fundo de Renda Fixa'), (3, 'Fundo Multimercado'), (4, 'Fundo Referenciado'), (5, 'Fundo da D\xedvida Externa'), (6, 'Fundo Cambial'), (7, 'Fundo de Curto Prazo')], verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='fundoinvestimento',
            name='situacao',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Em funcionamento normal'), (2, 'Fase pr\xe9-operacional'), (3, 'Terminado'), (4, 'Em situa\xe7\xe3o especial')], verbose_name='Situa\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='historicovalorcotas',
            name='valor_cota',
            field=models.DecimalField(decimal_places=15, max_digits=24, verbose_name='Valor da cota'),
        ),
    ]
