# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 05:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundo_investimento', '0003_auto_20170607_0010'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historicovalorcotas',
            unique_together=set([('fundo_investimento', 'data')]),
        ),
    ]
