# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 03:21
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundo_investimento', '0004_auto_20170607_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacaofundoinvestimento',
            name='quantidade',
            field=models.DecimalField(decimal_places=12, max_digits=21, verbose_name='Quantidade de cotas'),
        ),
        migrations.AlterField(
            model_name='operacaofundoinvestimento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor total da opera\xe7\xe3o'),
        ),
    ]
