# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-09 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundo_investimento', '0006_auto_20170704_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundoinvestimento',
            name='slug',
            field=models.SlugField(default='SLUG', max_length=100, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
