# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-09 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundo_investimento', '0007_fundoinvestimento_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fundoinvestimento',
            unique_together=set([('slug',), ('cnpj',)]),
        ),
    ]
