# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-30 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundo_investimento', '0008_auto_20180209_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundoinvestimento',
            name='situacao',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Em funcionamento normal'), (2, 'Fase pr\xe9-operacional'), (3, 'Cancelada'), (4, 'Em situa\xe7\xe3o especial')], verbose_name='Situa\xe7\xe3o'),
        ),
    ]
