# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-11 02:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fundo_investimento', '0009_auto_20181029_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=20, verbose_name='CNPJ')),
            ],
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=20, verbose_name='CNPJ')),
            ],
        ),
        migrations.CreateModel(
            name='GestorFundoInvestimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='fundoinvestimento',
            name='ultimo_registro',
        ),
        migrations.AddField(
            model_name='fundoinvestimento',
            name='data_cancelamento',
            field=models.DateField(blank=True, default=None, null=True, verbose_name=b'Data de cancelamento'),
        ),
        migrations.AddField(
            model_name='fundoinvestimento',
            name='data_registro',
            field=models.DateField(default=datetime.datetime(2018, 11, 11, 2, 8, 10, 108022, tzinfo=utc), verbose_name=b'Data de registro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fundoinvestimento',
            name='administrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fundo_investimento.Administrador'),
        ),
        migrations.AddField(
            model_name='gestorfundoinvestimento',
            name='fundo_investimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundo_investimento.FundoInvestimento'),
        ),
        migrations.AddField(
            model_name='gestorfundoinvestimento',
            name='gestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundo_investimento.Gestor'),
        ),
        migrations.AlterUniqueTogether(
            name='gestor',
            unique_together=set([('cnpj',)]),
        ),
        migrations.AlterUniqueTogether(
            name='auditor',
            unique_together=set([('cnpj',)]),
        ),
        migrations.AddField(
            model_name='fundoinvestimento',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fundo_investimento.Auditor'),
        ),
        migrations.AlterUniqueTogether(
            name='gestorfundoinvestimento',
            unique_together=set([('gestor', 'fundo_investimento')]),
        ),
    ]
