# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-11 02:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundo_investimento', '0010_auto_20181111_0008'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fundoinvestimento',
            unique_together=set([('slug',), ('cnpj', 'data_registro')]),
        ),
    ]
