# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('slug', models.CharField(max_length=30, unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaPostagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, unique=True, verbose_name='T\xedtulo')),
                ('slug', models.CharField(max_length=30, unique=True, verbose_name='Slug')),
                ('conteudo', models.TextField(verbose_name='Conte\xfado')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='postagem',
            unique_together=set([('slug',)]),
        ),
        migrations.AddField(
            model_name='categoriapostagem',
            name='postagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Postagem'),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together=set([('nome',), ('slug',)]),
        ),
    ]
