# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180123_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(max_length=30, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='slug',
            field=models.SlugField(max_length=30, unique=True, verbose_name='Slug'),
        ),
    ]
