# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180123_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='chamada_facebook',
            field=models.CharField(default='Texto do post para o facebook', max_length=250, verbose_name='Chamada no Facebook'),
            preserve_default=False,
        ),
    ]
