# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postagem_chamada_facebook'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaPostagem',
            new_name='CategoriaPost',
        ),
        migrations.RenameModel(
            old_name='Postagem',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='categoriapost',
            old_name='postagem',
            new_name='post',
        ),
        migrations.AlterUniqueTogether(
            name='categoriapost',
            unique_together=set([('post', 'categoria')]),
        ),
    ]
