# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180123_1329'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Tag',
        ),
        migrations.RenameModel(
            old_name='CategoriaPost',
            new_name='TagPost',
        ),
        migrations.RenameField(
            model_name='tagpost',
            old_name='categoria',
            new_name='Tag',
        ),
        migrations.AlterUniqueTogether(
            name='tagpost',
            unique_together=set([('post', 'Tag')]),
        ),
    ]
