# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180123_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagpost',
            old_name='Tag',
            new_name='tag',
        ),
        migrations.AlterUniqueTogether(
            name='tagpost',
            unique_together=set([('post', 'tag')]),
        ),
    ]
