# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-25 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180123_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=30, verbose_name='T\xedtulo'),
        ),
    ]
