# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-10 22:54
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bagogold', '0155_auto_20170903_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('descricao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descri\xe7\xe3o')),
                ('encerrado', models.BooleanField(default=False, verbose_name='Encerrado?')),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outros_investimentos', to='bagogold.Investidor')),
            ],
        ),
        migrations.CreateModel(
            name='OperacaoInvestimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantidade')),
                ('data', models.DateField(verbose_name='Data da opera\xe7\xe3o')),
                ('tipo_operacao', models.CharField(max_length=1, verbose_name='Tipo de opera\xe7\xe3o')),
                ('investimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outros_investimentos.Investimento')),
            ],
        ),
        migrations.CreateModel(
            name='OperacaoInvestimentoTaxa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor da taxa')),
                ('operacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='outros_investimentos.OperacaoInvestimento')),
            ],
        ),
        migrations.CreateModel(
            name='Rendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor do rendimento')),
                ('data', models.DateField(verbose_name='Data do rendimento')),
                ('investimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outros_investimentos.Investimento')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='investimento',
            unique_together=set([('nome', 'investidor')]),
        ),
    ]
