# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 00:18
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outros_investimentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amortizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor da amortiza\xe7\xe3o')),
                ('data', models.DateField(verbose_name='Data da amortiza\xe7\xe3o')),
                ('investimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outros_investimentos.Investimento')),
            ],
        ),
    ]
