# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outros_investimentos', '0002_amortizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investimento',
            name='encerrado',
        ),
        migrations.AddField(
            model_name='investimento',
            name='data_encerramento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de encerramento'),
        ),
    ]
