# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-17 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outros_investimentos', '0003_auto_20170915_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investimentotaxa',
            old_name='operacao',
            new_name='investimento',
        ),
    ]
