# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-22 14:07
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outros_investimentos', '0004_auto_20170917_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpostoRendaRendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=1, verbose_name='Tipo de c\xe1lculo')),
                ('rendimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='outros_investimentos.Rendimento')),
            ],
        ),
        migrations.CreateModel(
            name='ImpostoRendaValorEspecifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.DecimalField(decimal_places=3, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Percentual de IR')),
                ('imposto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='outros_investimentos.ImpostoRendaRendimento')),
            ],
        ),
    ]
