# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-28 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outros_investimentos', '0005_impostorendarendimento_impostorendavalorespecifico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impostorendarendimento',
            name='tipo',
            field=models.CharField(choices=[(b'L', 'Longo prazo'), (b'P', 'Percentual espec\xedfico')], max_length=1, verbose_name='Tipo de c\xe1lculo'),
        ),
    ]
