# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 03:03
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bagogold', '0152_auto_20170617_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criptomoeda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('ticker', models.CharField(max_length=10, verbose_name='Ticker')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoValorCriptomoeda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('valor', models.DecimalField(decimal_places=15, max_digits=24, verbose_name='Valor')),
                ('criptomoeda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criptomoeda.Criptomoeda')),
            ],
        ),
        migrations.CreateModel(
            name='OperacaoCriptomoeda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=12, max_digits=21, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantidade')),
                ('valor', models.DecimalField(decimal_places=15, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor unit\xe1rio')),
                ('data', models.DateField(verbose_name='Data da opera\xe7\xe3o')),
                ('tipo_operacao', models.CharField(max_length=1, verbose_name='Tipo de opera\xe7\xe3o')),
                ('criptomoeda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criptomoeda.Criptomoeda')),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criptomoeda', to='bagogold.Investidor')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='criptomoeda',
            unique_together=set([('ticker',)]),
        ),
        migrations.AlterUniqueTogether(
            name='historicovalorcriptomoeda',
            unique_together=set([('criptomoeda', 'data')]),
        ),
    ]
