# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-18 18:10
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criptomoeda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacaoCriptomoedaMoeda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criptomoeda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criptomoeda.Criptomoeda')),
            ],
        ),
        migrations.AddField(
            model_name='operacaocriptomoeda',
            name='taxa',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('1E-15'))], verbose_name='Taxa da opera\xe7\xe3o'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operacaocriptomoeda',
            name='quantidade',
            field=models.DecimalField(decimal_places=12, max_digits=21, validators=[django.core.validators.MinValueValidator(Decimal('1E-12'))], verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='operacaocriptomoeda',
            name='valor',
            field=models.DecimalField(decimal_places=15, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('1E-15'))], verbose_name='Valor unit\xe1rio'),
        ),
        migrations.AddField(
            model_name='operacaocriptomoedamoeda',
            name='operacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='criptomoeda.OperacaoCriptomoeda'),
        ),
    ]
