# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-23 05:16
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criptomoeda', '0003_auto_20170821_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacaocriptomoedataxa',
            name='valor',
            field=models.DecimalField(decimal_places=12, max_digits=21, validators=[django.core.validators.MinValueValidator(Decimal('1E-12'))], verbose_name='Taxa da opera\xe7\xe3o'),
        ),
    ]
