# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-23 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criptomoeda', '0004_auto_20170823_0216'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operacaocriptomoedataxa',
            unique_together=set([('operacao', 'moeda')]),
        ),
    ]
