# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 04:24
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criptomoeda', '0008_auto_20170824_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacaocriptomoeda',
            name='moeda_taxa',
        ),
        migrations.AlterField(
            model_name='operacaocriptomoeda',
            name='valor',
            field=models.DecimalField(decimal_places=12, max_digits=21, validators=[django.core.validators.MinValueValidator(Decimal('1E-12'))], verbose_name='Valor unit\xe1rio'),
        ),
        migrations.AlterField(
            model_name='operacaocriptomoedataxa',
            name='operacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='criptomoeda.OperacaoCriptomoeda'),
        ),
    ]
