# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-25 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criptomoeda', '0009_auto_20170824_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramInvestidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(verbose_name='ID do Telegram')),
            ],
        ),
        migrations.CreateModel(
            name='ValorDiarioCriptomoeda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Hor\xe1rio')),
                ('valor', models.DecimalField(decimal_places=12, max_digits=21, verbose_name='Valor em d\xf3lares')),
                ('criptomoeda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criptomoeda.Criptomoeda')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='operacaocriptomoedataxa',
            unique_together=set([]),
        ),
    ]
