# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-02 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criptomoeda', '0011_bot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operacaocriptomoeda',
            old_name='valor',
            new_name='preco_unitario',
        ),
    ]
