# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-02 17:06
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criptomoeda', '0012_auto_20170902_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacaocriptomoeda',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=12, max_digits=21, validators=[django.core.validators.MinValueValidator(Decimal('1E-12'))], verbose_name='Pre\xe7o unit\xe1rio'),
        ),
    ]
