# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-29 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criptomoeda', '0013_auto_20170902_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='valordiariocriptomoeda',
            name='moeda',
            field=models.CharField(default='USD', max_length=10, verbose_name='Moeda utilizada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='valordiariocriptomoeda',
            name='valor',
            field=models.DecimalField(decimal_places=12, max_digits=21, verbose_name='Valor'),
        ),
    ]
