# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-28 20:14
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criptomoeda', '0014_auto_20171029_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('quantidade', models.DecimalField(decimal_places=12, max_digits=21, validators=[django.core.validators.MinValueValidator(Decimal('1E-12'))], verbose_name='Quantidade recebida')),
                ('moeda_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moeda_origem_fork', to='criptomoeda.Criptomoeda')),
                ('moeda_recebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moeda_recebida_fork', to='criptomoeda.Criptomoeda')),
            ],
        ),
    ]
